### ISSUE TITLE
AHSD Not able to find streamDeck

### ISSUE THREAD

**Issue by micsen** [evilC/AutoHotStreamDeck#1]
Win 10 system 
StreamDeck XL

Line 12: GetDeck ([0-10])
Source: AutoHotStreamDeck
Description "Could not find device [0,1,2,3,4,5,6,7,8,9,10]" ==Tested 0-10
HelpFile: (null)
HelpContext: 0

**Comment by evilC** [comment]
Hi,   
The XL came out since the last release of AHSD, and as such, is not currently supported.  
AHSD uses OpenMacroBoard and the StreamDeckSharp SDK, which appear to have been updated to support the XL.  
As such, I think it is pretty much just a case of updating the libraries and rebuilding  
Do you have Discord? If so, ping me in [my channel](https://discord.gg/MmnhQYQ), and I will build a new copy and we can see if it works

**Comment by evilC** [comment]
Fixed in v0.3.2
